version: '3.3'

services:
  real-server:
    build:
      context: ./real-server
    image: kiphuong/real-server:latest  
    container_name: real-server-container
    ports:
      - "8443:4433"
    networks:
      poc-net:
        ipv4_address: 10.5.0.2
    volumes:
      - ./certs/real.crt:/app/real.crt
      - ./certs/real.key:/app/real.key

  fake-server:
    build:
      context: ./fake-server
    image: kiphuong/fake-server:latest  
    container_name: fake-server-container
    ports:
      - "9443:4433"
    networks:
      poc-net:
        ipv4_address: 10.5.0.3
    volumes:
      - ./certs/fake.crt:/app/fake.crt
      - ./certs/fake.key:/app/fake.key

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kiphuong/client:latest       
    container_name: client-container
    stdin_open: true
    tty: true
    networks:
      poc-net:
        ipv4_address: 10.5.0.4
    volumes:
      - ./certs/pinnedkey.pem:/root/pinnedkey.pem

networks:
  poc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

